Features/add linters
GenesisEducationKyiv/software-engineering-school-4-0-AndrewSergienko pull request #5
Opened 2024-06-09 20:29 UTC by AndrewSergienko

refactor code by linters. Add linters checking workflow to CI

2024-06-10 13:26 UTC, andriihar commented on main.go
> +		log.Fatal(err)
What will happen in log.Fatal() func?  

You can read about os.Exit(1) 

https://go.dev/play/p/pwfwPbQ8nnb

2024-06-10 13:26 UTC, andriihar commented on src/adapters/email.go
> +	//println(fmt.Sprintf("Send email from: %s; to: %s; rate: %f", ea.Username, target, rate))
Do we need this comment?

2024-06-10 15:15 UTC, andriihar commented on src/adapters/email.go
> +		log.Fatal(err)
What will happen in log.Fatal() func?

You can read about os.Exit(1)

https://go.dev/play/p/pwfwPbQ8nnb

2024-06-10 21:43 UTC, AlwaysSayNo requested changes

2024-06-10 21:43 UTC, AlwaysSayNo commented on .github/workflows/linters.yaml
> +    branches: ["project"]
I couldn't find "project" branch in your project. Maybe you need to use "main" instead?

2024-06-10 21:43 UTC, AlwaysSayNo commented on .github/workflows/linters.yaml
> +        run: go test -v ./...
I'm not sure, but I think you don't need to have build+test stage for linter action. Probably you could create a separate action for this.

2024-06-13 12:39 UTC, andriihar approved these changes

2024-06-13 12:48 UTC, andriihar commented
For the future, you can add linters you want to use and configure them.

2024-06-14 11:57 UTC, merged